language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  

before_install:
  - pip install codecov
  - python setup.py install
  
  
script:
  - cd tests/
  - nosetests



sudo: required
